#! /bin/bash

function usage_
{
    echo "usage: clup [-e][-c][-x] [-R] [directory1 [ ... [directoryN]]]"
    echo "  where -e (default mode) will clean up emacs files (*~, etc.)"
    echo "  where -s will clean up source code revision files (svn-commit*tmp, etc.)"
    echo "  where -c will clean up intermediate compiled files (*.o, etc.)"
    echo "  where -x will clean up intermediate TeX/LaTeX files (*.toc, etc.)"
    echo "  where -R will recurse through all directories"
}

#  needs $RE to be set
function cleanup_
{
    DIR=$1
    if test x$DIR != "x" ; then
        pushd $DIR > /dev/null
    fi
    echo "[$PWD]"
    rm -v -f $RE 2> /dev/null
    if test x$DIR != "x" ; then
        popd > /dev/null
    fi
}

NOARG=1
DO_EMACS=0
DO_COMPILED=0
DO_LATEX=0
RECURSE=0
DO_SVN=0

while getopts "ecxRs" OPTION ; do
    case $OPTION in
        e)
        NOARG=0
        DO_EMACS=1
        ;;
        c)
        NOARG=0
        DO_COMPILED=1
        ;;
        x)
        NOARG=0
        DO_LATEX=1
        ;;
        R)
        RECURSE=1
        ;;
        s)
        NOARG=0
        DO_SVN=1
        ;;
        ?)
        usage_
        exit 1
        ;;
    esac
done

shift $(( $OPTIND - 1 ))

#  default behavior
if test $NOARG -eq 1  ; then
    DO_EMACS=1 
    DO_SVN=1 
fi

if test $DO_EMACS -eq 1  ; then
    RE="$RE *~ .*~ \#*\#"
fi

if test $DO_COMPILED -eq 1 ; then
    RE="$RE *.o *.s *.d *.err *.class *.obj"
fi

if test $DO_LATEX -eq 1 ; then
    RE="$RE *.aux *.dvi *.out *.toc *.log"
fi

if test $DO_SVN -eq 1 ; then
    RE="$RE svn-commit*.tmp"
fi

if test $# -gt 0 ; then
    for dir in $@ ; do
        if test -d $dir ; then
            if test $RECURSE -eq 1 ; then
                #  will include $dir
                for d in $( find $dir -type d -print | fgrep -v '.svn' ) ; do
                    cleanup_ $d
                done
            else
                cleanup_ $dir
            fi
        else
            echo "could not find directory '$dir'"
        fi
    done
else
    cleanup_
fi

exit 0
