#! /bin/bash

function usage_
{
    echo "usage: clup [-e] [-c] [directory1 [ ... [directoryN]]]"
    echo "  where -e (default mode) will clean up emacs files (*~, etc.)"
    echo "  where -c will clean up intermediate compiled files (*.o, etc.)"
}

#  needs $RE to be set
function cleanup_
{
    echo "[$PWD]"
    ls $RE 2> /dev/null
    rm -f $RE 2> /dev/null
}

NOARG=1
DO_EMACS=0
DO_COMPILED=0

while getopts "ec" OPTION ; do
    case $OPTION in
        e)
        NOARG=0
        DO_EMACS=1
        ;;
        c)
        NOARG=0
        DO_COMPILED=1
        ;;
        ?)
        usage_
        exit 1
        ;;
    esac
done

shift $(( $OPTIND - 1 ))

#  default behavior
if test $NOARG -eq 1  ; then
    DO_EMACS=1 
fi

if test $DO_EMACS -eq 1  ; then
    RE="$RE *~ .*~ \#*\#"
fi

if test $DO_COMPILED -eq 1 ; then
    RE="$RE *.o *.s *.d *.err *.class"
fi

if test $# -gt 0 ; then
    for dir in $@ ; do
        if test -a $dir ; then
            if test -d $dir ; then
                pushd $dir > /dev/null
                cleanup_
                popd > /dev/null
            fi
        else
            echo "could not find directory '$dir'"
        fi
    done
else
    cleanup_
fi

exit 0
