#! /bin/bash

DOTDIR=${HOME}/.dotfiles
BINDIR=${HOME}/bin

cd $HOME

rm -f .bashrc
ln ${DOTDIR}/.bashrc ${HOME}

rm -f bin/clup
ln ${DOTDIR}/clup ${BINDIR}

rm -f .emacs
ln ${DOTDIR}/.emacs ${HOME}

rm -f .exrc
ln ${DOTDIR}/.exrc ${HOME}

rm -f .mwmrc
ln ${DOTDIR}/.mwmrc ${HOME}

rm -f .twmrc
ln ${DOTDIR}/.twmrc ${HOME}

rm -f .Xdefaults
ln ${DOTDIR}/.Xdefaults ${HOME}

rm -f .xmodmap4win
ln ${DOTDIR}/.xmodmap4win ${HOME}

rm -f .inputrc
ln ${DOTDIR}/.inputrc ${HOME}

rm -f .sawfishrc
ln ${DOTDIR}/.sawfishrc ${HOME}
