#! /bin/bash

cd $HOME

rm .bashrc
ln -s dotfiles/.bashrc .

rm bin/clup
ln -s ../dotfiles/clup bin

rm .emacs
ln -s dotfiles/.emacs .

rm .exrc
ln -s dotfiles/.exrc .

rm .mwmrc
ln -s dotfiles/.mwmrc .

rm .twmrc
ln -s dotfiles/.twmrc .

rm .Xdefaults
ln -s dotfiles/.Xdefaults .

rm .xmodmap4win
ln -s dotfiles/.xmodmap4win .

rm .inputrc
ln -s dotfiles/.inputrc .
