;;; windsize-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from windsize.el

(autoload 'windsize-left "windsize" "\
Resize the current window by moving one of its edges to the left.

(fn &optional ARG)" t)
(autoload 'windsize-right "windsize" "\
Resize the current window by moving one of its edges to the right.

(fn &optional ARG)" t)
(autoload 'windsize-up "windsize" "\
Resize the current window by moving one of its edges up.

(fn &optional ARG)" t)
(autoload 'windsize-down "windsize" "\
Resize the current window by moving one of its edges down.

(fn &optional ARG)" t)
(autoload 'windsize-default-keybindings "windsize" nil t)
(register-definition-prefixes "windsize" '("windsize-"))

;;; End of scraped data

(provide 'windsize-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; windsize-autoloads.el ends here
