;;; crystal-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from crystal-mode.el

(autoload 'crystal-tool-format "crystal-mode" "\
Format the contents of the current buffer without persisting the result." t)
(autoload 'crystal-tool-expand "crystal-mode" "\
Expand macro at point." t)
(autoload 'crystal-tool-imp "crystal-mode" "\
Show implementations at point." t)
(autoload 'crystal-tool-context "crystal-mode" "\
Show content at point." t)
(autoload 'crystal-def-jump "crystal-mode" "\
Jump to the definition of the expression at POINT.

(fn POINT &optional OTHER-WINDOW)" t)
(autoload 'crystal-def-jump-other-window "crystal-mode" "\


(fn POINT)" t)
(autoload 'crystal-spec-switch "crystal-mode" "\
Switch source file and its spec file." t)
(autoload 'crystal-spec-line "crystal-mode" "\
Run spec on current line." t)
(autoload 'crystal-spec-buffer "crystal-mode" "\
Run spec for current buffer." t)
(autoload 'crystal-spec-all "crystal-mode" "\
Run all specs for current project." t)
(autoload 'crystal-mode "crystal-mode" "\
Major mode for editing Crystal code.

\\{crystal-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist (cons (purecopy "\\(?:\\.cr\\)\\'") 'crystal-mode))
(dolist (name (list "crystal")) (add-to-list 'interpreter-mode-alist (cons (purecopy name) 'crystal-mode)))
(register-definition-prefixes "crystal-mode" '("crystal-"))

;;; End of scraped data

(provide 'crystal-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; crystal-mode-autoloads.el ends here
