;;; sort-words-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sort-words.el

(autoload 'sort-words "sort-words" "\
Sort words in region alphabetically.
Then insert them replacing the existing region.
START and END are boundries of the selected region.

(fn START END)" t)
(register-definition-prefixes "sort-words" '("sort-words-"))

;;; End of scraped data

(provide 'sort-words-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sort-words-autoloads.el ends here
