(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-delay 0.5)
 '(ac-trigger-key "")
 '(browse-url-temp-dir "/home/flavorjones/tmp")
 '(create-lockfiles nil)
 '(dired-listing-switches "-alG")
 '(dired-use-ls-dired t)
 '(electric-pair-pairs '((34 . 34) (8216 . 8217) (8220 . 8221) (96 . 96)))
 '(electric-pair-text-pairs '((34 . 34) (8216 . 8217) (8220 . 8221) (96 . 96)))
 '(fill-column 100)
 '(frame-inhibit-implied-resize t)
 '(frame-resize-pixelwise t)
 '(fringe-mode nil nil (fringe))
 '(git-link-open-in-browser t)
 '(global-goto-address-mode t)
 '(global-undo-tree-mode t)
 '(goto-address-fontify-p nil)
 '(goto-address-highlight-p nil)
 '(highlight-indent-guides-method 'character)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-major-mode 'gfm-mode)
 '(initial-scratch-message "# scratch buffer\12")
 '(ispell-highlight-face 'flyspell-incorrect)
 '(js2-auto-indent-flag nil)
 '(js2-enter-indents-newline nil)
 '(js2-mirror-mode nil)
 '(js2-mode-indent-ignore-first-tab t)
 '(lsp-enable-indentation nil)
 '(markdown-fontify-code-blocks-natively t)
 '(markdown-link-space-sub-char "-")
 '(markdown-wiki-link-search-subdirectories t)
 '(neo-autorefresh t)
 '(neo-keymap-style 'concise)
 '(neo-smart-open t)
 '(neo-theme 'arrow)
 '(neo-window-fixed-size nil)
 '(org-agenda-files '("~/docs/notes/todo.org"))
 '(org-file-apps
   '(("txt" . emacs)
     ("tex" . emacs)
     ("ltx" . emacs)
     ("org" . emacs)
     ("el" . emacs)
     ("bib" . emacs)
     ("pdf" . "evince '%s'")))
 '(org-hide-leading-stars t)
 '(org-log-done 'time)
 '(org-odd-levels-only t)
 '(org-startup-folded 'content)
 '(package-selected-packages
   '(swift-mode sort-words mise windsize diminish ligature zig-mode which-key minitest rust-mode lsp-ui lsp-mode nginx-mode copilot quelpa-use-package quelpa monokai-theme night-owl-theme atomic-chrome protobuf-mode bison-mode git-link poly-ruby polymode hide-mode-line projectile-rails edit-indirect editorconfig rubocopfmt interaction-log bazel-mode ivy json-mode projectile nix-mode auto-compile crystal-mode csharp-mode direnv dockerfile-mode elm-mode exec-path-from-shell feature-mode go-mode haml-mode hl-todo julia-mode lua-mode magit markdown-toc neotree powershell rspec-mode ruby-hash-syntax sass-mode use-package yaml-mode markdown-mode udev-mode bicycle web-mode solarized-theme gnu-elpa-keyring-update ruby-additional ruby-end ruby-refactor rvm slim-mode toml-mode unicode-fonts markdown-mode+ go-autocomplete go-snippets golint gitattributes-mode gitconfig-mode gitignore-mode flymake-ruby rufo flycheck-julia undo-tree rnc-mode org minimap git-blame css-mode auto-highlight-symbol))
 '(paradox-github-token t)
 '(pixel-scroll-mode t)
 '(pixel-scroll-precision-mode t)
 '(projectile-rails-global-mode t)
 '(remote-file-name-inhibit-locks t)
 '(ring-bell-function 'ignore)
 '(rubocopfmt-use-bundler-when-possible nil)
 '(ruby-align-to-stmt-keywords t)
 '(ruby-flymake-use-rubocop-if-available nil)
 '(safe-local-variable-values
   '((frozen_string_literal . true)
     (eval c-set-offset 'inlambda 0)
     (eval c-set-offset 'access-label '-)
     (eval c-set-offset 'substatement-open 0)
     (eval c-set-offset 'arglist-cont-nonempty '+)
     (eval c-set-offset 'arglist-cont 0)
     (eval c-set-offset 'arglist-intro '+)
     (eval c-set-offset 'inline-open 0)
     (eval c-set-offset 'defun-open 0)
     (eval c-set-offset 'innamespace 0)
     (indicate-empty-lines . t)
     (whitespace-line-column . 80)
     (eval when
           (fboundp 'rainbow-mode)
           (rainbow-mode 1))
     (require-final-newline . t)
     (mangle-whitespace . t)
     (encoding . utf-8)
     (ruby-compilation-executable . "ruby")
     (ruby-compilation-executable . "ruby1.8")
     (ruby-compilation-executable . "ruby1.9")
     (ruby-compilation-executable . "rbx")
     (ruby-compilation-executable . "jruby")))
 '(sh-basic-offset 2)
 '(solarized-scale-org-headlines nil)
 '(solarized-use-variable-pitch nil)
 '(undo-tree-visualizer-diff t)
 '(undo-tree-visualizer-timestamps t)
 '(visual-line-fringe-indicators '(nil right-curly-arrow))
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-auto-indentation nil)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-sql-indent-offset 2)
 '(web-mode-tests-directory "~/tests/"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "JetBrains Mono" :foundry "JB  " :slant normal :weight medium :height 69 :width normal))))
 '(copilot-overlay-face ((t (:inherit (shadow highlight italic))))))
