# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  common_config = ->(vm, box_name, addy) do
    vm.box     = box_name
    vm.box_url = "http://files.vagrantup.com/#{box_name}.box"
    vm.share_folder "code",   "/home/vagrant/code",   "#{ENV['HOME']}/code", :nfs => true
    vm.share_folder "shared", "/home/vagrant/shared", "#{ENV['HOME']}/Shared/Virtualboxen", :nfs => true
    vm.customize ["modifyvm", :id, "--cpus", 2]
    vm.customize ["modifyvm", :id, "--name", box_name]
    vm.network :hostonly, addy
  end

  config.vm.define :lucid32 do |config|
    common_config.call config.vm, "lucid32", "33.33.33.11"
  end

  config.vm.define :precise64 do |config|
    common_config.call config.vm, "precise64", "33.33.33.12"
  end
end
